### ISSUE TITLE
I have installed the newest version and app is in English not in Polish

### ISSUE THREAD

**Issue by atlochowski** [CODeRUS/personal-ringtones#1]
I have installed the newest version and app is in English not in Polish. My OS is set to Polish lang.

**Comment by CODeRUS** [comment]
maybe wrong polish in translations? what is your locale code?

**Comment by CODeRUS** [comment]
check 1.2.3 versoin, i moved transltions languages and teams in traansifex to proper ones.

**Comment by atlochowski** [comment]
it's ok now.
