### ISSUE TITLE
Featue request: Strip spaces from numbers on inport

### ISSUE THREAD

**Issue by mschilli87** [CODeRUS/personal-ringtones#3]
Dear @CODeRUS,

First of all, thank you for providing this app (and so much more). :heart:

It is working just fine but comes with one inconvenience that I think would be easier to fix on the app's end than the user's:

I understand the app cannot resolve local numbers but requires the full international number.
That is fine with me since I store the full number in my phone book either way.
However, sometimes I still need to make local calls from landline phones. In this case I end up manually dialing the number from my phone book. In such cases I prefer to dial the 'final part' only, skipping the country and area codes.
[As you pointed out elsewhere](https://openrepos.net/comment/31186#comment-31186), it is generally not possible to know the length of that part upfront. My solution to this problem is to store the phone number in international with spaces separating the individual parts: A number from Berlin would be saved as `+49 30 12345678` while another one from a smaller town like Potsdam could be `+49 331 123456`. This way, I know I only need to call 123456 when placing a local call within Potsdam, without having to know the local area code (or rather its length).

Unfortunately, assigning a personal ringtone to `+49 331 123456` results in the default ringtone being used when receiving a call from that number. When I modify the contact to `+49331123456` and re-configure the personal ringtone, it works just fine.

So while I *can* modify my entire address book to not use spaces, I'd very much prefer the personal ringtones app to simply ignore them. As the app does not 'track' changes made to contact's numbers, I understand it is maintaining its own database of numbers associated to the corresponding ringtones and the contact list ('phone book') is rather used as just a reference to import numbers from. In this case, simply removing spaces from number upon import should fix my issue. To me this sounds like a one-line change.

I have no experience with SFOS app development and couldn't find anything that looked like the actual import code (rather than just UI specifications) when browsing this repository. Otherwise, I would have submitted a pull request along with this issue.
Given a pointer where to look, I'd happily contribute this myself.

Thank you very much in advance for considering this suggestion and for you contributions to the SFOS ecosystem in general.

Best,
Marcel

**Comment by CODeRUS** [comment]
hello!

please try modifying `PersonalRingtones.qml` file at line 45. paste new line with `number = number.replace(" ", "")`

let me know if it works, also interested if person name is detected by stripped number or not

**Comment by mschilli87** [comment]
@CODeRUS: Thx! I'll give it a try in the next weeks and report back.

**Comment by mschilli87** [comment]
@CODeRUS: Your suggested change did not work for me because it only replaces the first occurence. Adding that line twice resulted in the desired effect buy feels hacky. I did try `number.replaceAll(" ", "")` and  `number.remove(" ")` but neither seem to be available in QML. I have no experience with Qt/QML and barely know any Javascript so I have given up improving this myself. I quick web search led me to [this SO question](https://stackoverflow.com/q/66244180/2451238) which was unanswered as well, so I added a bounty. Maybe this will lead to a better solution (if you don't know any already :wink:).

**Comment by CODeRUS** [comment]
okay, then do:
```
        while (number.indexOf(" ") > 0) {
            number= number.replace(" ", "")
        }
```

**Comment by CODeRUS** [comment]
or with regexp:
`number = number.replace(/[^0-9+]/g, "")`

**Comment by mschilli87** [comment]
How do you like `number = number.split(" ").join("")`? There are probably many hacks. I was just surprised no simple `replaceAll(pat, sub)` exists alongside `replace(pat, sub)`.

---
**edit**: [This](https://stackoverflow.com/a/1144788/2451238) appears to be a good summary.

PS: @CODeRUS: Do you want me to create a PR for this change or rather for me to maintain my own patch?

**Comment by CODeRUS** [comment]
regexp is better

**Comment by CODeRUS** [comment]
you can PR, but no release in openrepos before i can find aarch64 device for testing :D

**Comment by mschilli87** [comment]
@CODeRUS:
> regexp is better

I agree, that why I gave that suggestion a :heart:. :wink:


> you can PR

[Done](https://github.com/CODeRUS/personal-ringtones/pull/4). :slightly_smiling_face: 


> but no release in openrepos before i can find aarch64 device for testing :D

No worries, I have it on my device now and as long as it will be in the next release, I don't need to remember changing it manually again after the next update. :wink:


Thank you for your fast responses, great mentoring regarding dipping my feet into this codebase, and being open for feature suggestions like this one. :1st_place_medal: 

---
**edit**: I left the issue open since it should close automatically once my PR is merged, but feel free to close before that. From my point of view, this is resolved. :smile:

**Comment by CODeRUS** [comment]
thanks
